### PR TITLE
Add screenshots in readme #1  and Add setup process in readme #2 fixed

### PR DESCRIPTION
**Pull request by CoderRedwing**
your both issue fixd kindly accept the pr

### CODE REVIEW

**Review by Devansh-Baghel — CHANGES_REQUESTED** [review]
Thanks for contributing, but the readme is not properly formatted, it should look similar to [this setup](https://github.com/Devansh-Baghel/memory-game#setup) with terminal commands being inside code blocks.

Also can you please crop screenshots to not have the browser and dock/taskbar of your OS.

**Comment by CoderRedwing** [comment]
i can do this if you want

**Comment by Devansh-Baghel** [comment]
> i can do this if you want

@CoderRedwing  I didn't told you not to do it, i just requested changes, make the changes commit them, and push them, it should then automatically appear here in this pr.

**Review by Devansh-Baghel — COMMENTED** [review]
You really just copy pasted [this readme](https://github.com/a-s-t-e-y-a/infoB-J-P#readme), without even changing the link to that repo. I'm closing this pr.

**Comment by CoderRedwing** [comment]
its not fair yrr kr to diya yrr jaise bola tha yrr

**Comment by CoderRedwing** [comment]
budy this my friend i just do it not copied

**Pull request closed without merging**
